[package]
name = "to-do-dapp-package"
version = "0.1.0"
authors = ["Alessandro Baldassarre <alessandro.baldassarre.dev@gmail.com>"]
edition = "2021"

[dependencies]
cosmwasm-schema = "1.1.3"
cosmwasm-std = "1.1.3"
cosmwasm-storage = "1.1.3"
cw-storage-plus = "1.0.1"
cw2 = "1.0.1"
cw-controllers = "1.0.1"
cw-utils = "1.0.1"
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }

[dev-dependencies]
cw-multi-test = "0.16.2"
